#!/usr/bin/env python3
"""Compute Wasserstein-vs-oracle metrics and visualize them by simulation case.

The script always requires distribution sample outputs generated by:
  - marginal_source=deepcf
  - marginal_source=tabpfn-naive
  - marginal_source=oracle

If marginal_source=div files are present, it also computes DIV-vs-oracle distances.
With --require-div, DIV becomes part of the completeness check.

Oracle reference is defined as:
  marginal_source=oracle, model=oracle

The oracle sample rows are expected to be direct samples from the true
interventional law under do(X=x), not Gaussian-copula reconstructions.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
from dataclasses import dataclass
from pathlib import Path
import sys
from typing import Dict, Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from multivar.core.dgp import normalize_dgp_code


REQUIRED_BASE_SOURCES = ("deepcf", "tabpfn-naive", "oracle")
KNOWN_EXTRA_CORE_SOURCES = ("tabpfn_real", "tabicl")
OPTIONAL_SOURCES = ("div",)
ALLOWED_SOURCES = REQUIRED_BASE_SOURCES + KNOWN_EXTRA_CORE_SOURCES + OPTIONAL_SOURCES
META_COLS = ("dgp_code", "n_train", "seed", "rho_eps", "marginal_source")
SAMPLE_COLS = ("x", "model", "y1", "y2", "sample_weight")
EPS = 1e-12
EXTRA_SOURCE_LABELS = {
    "tabpfn_real": "TabCF (Real-TabPFNv2.5) vs Oracle",
    "tabicl": "TabCF (TabICLv2) vs Oracle",
}
EXTRA_SOURCE_COLORS = {
    "tabpfn_real": "#8c564b",
    "tabicl": "#17becf",
}


@dataclass(frozen=True)
class CaseKey:
    dgp_code: str
    n_train: int
    seed: int
    rho_eps_key: float


def _round_key(value: float, digits: int = 10) -> float:
    return round(float(value), digits)


def _stable_seed(base_seed: int, *parts: object) -> int:
    msg = "|".join(str(p) for p in parts).encode("utf-8")
    digest = hashlib.sha1(msg).hexdigest()
    return (int(base_seed) + int(digest[:8], 16)) % (2**32 - 1)


def _rho_tag(value: float) -> str:
    sign = "m" if value < 0 else ""
    text = f"{abs(value):.6f}".rstrip("0").rstrip(".")
    text = text.replace(".", "p")
    if not text:
        text = "0"
    return f"{sign}{text}"


def _normalize_weights(weights: np.ndarray) -> np.ndarray:
    w = np.asarray(weights, dtype=float).reshape(-1)
    if w.size == 0:
        return w
    total = float(np.sum(w))
    if not np.isfinite(total) or total <= 0.0:
        return np.full(w.size, 1.0 / float(w.size), dtype=float)
    return w / total


def _is_uniform_weights(weights: np.ndarray, tol: float = 1e-10) -> bool:
    w = _normalize_weights(weights)
    if w.size == 0:
        return False
    target = 1.0 / float(w.size)
    return bool(np.max(np.abs(w - target)) <= tol)


def _downsample_points(
    points: np.ndarray,
    weights: np.ndarray,
    *,
    max_n: int | None,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    pts = np.asarray(points, dtype=float)
    w = _normalize_weights(weights)
    if max_n is None or max_n <= 0 or len(pts) <= max_n:
        return pts, w

    rng = np.random.default_rng(seed)
    idx = rng.choice(len(pts), size=int(max_n), replace=False, p=w)
    pts_sub = pts[idx]
    w_sub = _normalize_weights(w[idx])
    return pts_sub, w_sub


def _sliced_wasserstein_fast_uniform(
    points_a: np.ndarray,
    points_b: np.ndarray,
    directions: np.ndarray,
) -> float:
    proj_a = points_a @ directions.T
    proj_b = points_b @ directions.T
    proj_a.sort(axis=0)
    proj_b.sort(axis=0)
    per_proj = np.mean(np.abs(proj_a - proj_b), axis=0)
    return float(np.mean(per_proj))


def _sliced_wasserstein_general(
    points_a: np.ndarray,
    points_b: np.ndarray,
    weights_a: np.ndarray,
    weights_b: np.ndarray,
    directions: np.ndarray,
) -> float:
    proj_a = points_a @ directions.T
    proj_b = points_b @ directions.T
    vals = []
    for j in range(directions.shape[0]):
        vals.append(
            stats.wasserstein_distance(
                proj_a[:, j],
                proj_b[:, j],
                u_weights=weights_a,
                v_weights=weights_b,
            )
        )
    return float(np.mean(vals)) if vals else np.nan


def compute_wasserstein_distance(
    points_a: np.ndarray,
    points_b: np.ndarray,
    weights_a: np.ndarray,
    weights_b: np.ndarray,
    *,
    method: str,
    directions: np.ndarray | None,
) -> float:
    pa = np.asarray(points_a, dtype=float)
    pb = np.asarray(points_b, dtype=float)
    wa = _normalize_weights(weights_a)
    wb = _normalize_weights(weights_b)

    if pa.ndim != 2 or pb.ndim != 2 or pa.shape[1] != 2 or pb.shape[1] != 2:
        raise ValueError(
            "Expected 2D point arrays with shape (n, 2); "
            f"got {pa.shape} and {pb.shape}"
        )
    if pa.shape[0] == 0 or pb.shape[0] == 0:
        return np.nan

    if method == "nd":
        fn = getattr(stats, "wasserstein_distance_nd", None)
        if fn is None:
            raise RuntimeError(
                "scipy.stats.wasserstein_distance_nd is unavailable in current SciPy version. "
                "Use --method sliced or upgrade SciPy."
            )
        return float(fn(pa, pb, u_weights=wa, v_weights=wb))

    if method != "sliced":
        raise ValueError(f"Unsupported method: {method}")
    if directions is None or directions.size == 0:
        raise ValueError("sliced method requires non-empty projection directions")

    if _is_uniform_weights(wa) and _is_uniform_weights(wb) and len(pa) == len(pb):
        return _sliced_wasserstein_fast_uniform(pa, pb, directions)
    return _sliced_wasserstein_general(pa, pb, wa, wb, directions)


def _build_projection_directions(n_projections: int, seed: int) -> np.ndarray:
    if n_projections <= 0:
        raise ValueError(f"n_projections must be positive, got {n_projections}")
    rng = np.random.default_rng(seed)
    dirs = rng.normal(0.0, 1.0, size=(int(n_projections), 2))
    norms = np.linalg.norm(dirs, axis=1, keepdims=True)
    norms = np.maximum(norms, EPS)
    return dirs / norms


def _normalize_extra_core_sources(values: Iterable[str] | None) -> tuple[str, ...]:
    if values is None:
        return ()
    out: list[str] = []
    seen = set()
    for value in values:
        source = str(value).strip().lower()
        if not source:
            continue
        if source not in KNOWN_EXTRA_CORE_SOURCES:
            raise ValueError(
                f"Unsupported extra core source '{value}'. "
                f"Expected one of {KNOWN_EXTRA_CORE_SOURCES}."
            )
        if source not in seen:
            out.append(source)
            seen.add(source)
    return tuple(out)


def _required_sources(*, require_div: bool, extra_core_sources: Iterable[str] = ()) -> tuple[str, ...]:
    extra_sources = _normalize_extra_core_sources(extra_core_sources)
    if require_div:
        return ("deepcf", "tabpfn-naive") + extra_sources + ("div", "oracle")
    return REQUIRED_BASE_SOURCES + extra_sources


def _normalize_dgp_codes(values: Iterable[str] | None) -> tuple[str, ...] | None:
    if values is None:
        return None
    return tuple(normalize_dgp_code(value) for value in values)


def discover_case_files(per_run_dir: Path) -> tuple[dict[CaseKey, dict[str, Path]], int]:
    case_files: dict[CaseKey, dict[str, Path]] = {}
    skipped = 0
    paths = sorted(per_run_dir.glob("multivar_*_distribution_samples.csv"))

    for path in paths:
        try:
            meta = pd.read_csv(path, usecols=list(META_COLS), nrows=1)
        except Exception:
            skipped += 1
            continue
        if meta.empty:
            skipped += 1
            continue
        row = meta.iloc[0].to_dict()
        if any(col not in row for col in META_COLS):
            skipped += 1
            continue

        source = str(row["marginal_source"]).strip().lower()
        if source not in ALLOWED_SOURCES:
            skipped += 1
            continue

        key = CaseKey(
            dgp_code=str(row["dgp_code"]),
            n_train=int(row["n_train"]),
            seed=int(row["seed"]),
            rho_eps_key=_round_key(float(row["rho_eps"])),
        )
        source_map = case_files.setdefault(key, {})

        prev = source_map.get(source)
        if prev is None or path.stat().st_mtime >= prev.stat().st_mtime:
            source_map[source] = path

    return case_files, skipped


def filter_case_files(
    case_files: dict[CaseKey, dict[str, Path]],
    *,
    n_train: int | None,
    dgp_codes: Iterable[str] | None,
) -> dict[CaseKey, dict[str, Path]]:
    allowed_dgp_codes = set(_normalize_dgp_codes(dgp_codes) or ())
    filtered: dict[CaseKey, dict[str, Path]] = {}

    for key, source_map in case_files.items():
        if n_train is not None and int(key.n_train) != int(n_train):
            continue
        if allowed_dgp_codes and key.dgp_code not in allowed_dgp_codes:
            continue
        filtered[key] = dict(source_map)
    return filtered


def load_model_samples_by_x(path: Path, model: str) -> dict[float, tuple[float, np.ndarray, np.ndarray]]:
    df = pd.read_csv(path, usecols=list(SAMPLE_COLS))
    sub = df[df["model"] == model]
    if sub.empty:
        return {}

    grouped: dict[float, tuple[float, np.ndarray, np.ndarray]] = {}
    for x_val, grp in sub.groupby("x", sort=True):
        x_float = float(x_val)
        x_key = _round_key(x_float, digits=12)
        points = grp[["y1", "y2"]].to_numpy(dtype=float)
        weights = _normalize_weights(grp["sample_weight"].to_numpy(dtype=float))
        grouped[x_key] = (x_float, points, weights)
    return grouped


def _iter_complete_cases(
    case_files: dict[CaseKey, dict[str, Path]],
    *,
    require_div: bool,
    extra_core_sources: Iterable[str] = (),
) -> Iterable[tuple[CaseKey, dict[str, Path]]]:
    required_sources = _required_sources(require_div=require_div, extra_core_sources=extra_core_sources)
    for key in sorted(case_files, key=lambda k: (k.dgp_code, k.n_train, k.rho_eps_key, k.seed)):
        source_map = case_files[key]
        if all(src in source_map for src in required_sources):
            yield key, source_map


def select_complete_cases(
    case_files: dict[CaseKey, dict[str, Path]],
    *,
    require_div: bool,
    extra_core_sources: Iterable[str],
) -> list[tuple[CaseKey, dict[str, Path]]]:
    extra_sources = _normalize_extra_core_sources(extra_core_sources)
    return list(
        _iter_complete_cases(
            case_files,
            require_div=require_div,
            extra_core_sources=extra_sources,
        )
    )


def shard_complete_cases(
    complete_cases: list[tuple[CaseKey, dict[str, Path]]],
    *,
    shard_count: int,
    shard_index: int,
) -> list[tuple[CaseKey, dict[str, Path]]]:
    if shard_count < 1:
        raise ValueError(f"shard_count must be >= 1, got {shard_count}")
    if shard_index < 0 or shard_index >= shard_count:
        raise ValueError(
            f"shard_index must be in [0, {shard_count - 1}], got {shard_index}"
        )
    if shard_count == 1:
        return list(complete_cases)
    return [item for idx, item in enumerate(complete_cases) if idx % shard_count == shard_index]


def load_detail_parts(glob_pattern: str) -> pd.DataFrame:
    paths = [Path(path) for path in sorted(glob.glob(glob_pattern))]
    if not paths:
        raise FileNotFoundError(f"No detail CSV files matched pattern: {glob_pattern}")
    dfs = [pd.read_csv(path) for path in paths if path.exists() and path.stat().st_size > 0]
    if not dfs:
        raise RuntimeError(f"All matched detail CSV files are empty: {glob_pattern}")
    detail_df = pd.concat(dfs, ignore_index=True)
    if detail_df.empty:
        raise RuntimeError(f"Merged detail CSV is empty for pattern: {glob_pattern}")
    sort_cols = [col for col in ["dgp_code", "n_train", "rho_eps", "seed", "x"] if col in detail_df.columns]
    if sort_cols:
        detail_df = detail_df.sort_values(sort_cols).reset_index(drop=True)
    return detail_df


def compute_seed_x_metrics(
    case_files: dict[CaseKey, dict[str, Path]] | None,
    *,
    require_div: bool,
    extra_core_sources: Iterable[str],
    method: str,
    directions: np.ndarray | None,
    max_samples_per_dist: int | None,
    random_seed: int,
    complete_cases: list[tuple[CaseKey, dict[str, Path]]] | None = None,
) -> pd.DataFrame:
    rows: list[dict[str, float | int | str]] = []
    extra_sources = _normalize_extra_core_sources(extra_core_sources)
    if complete_cases is None:
        if case_files is None:
            raise ValueError("Provide either case_files or complete_cases")
        complete_cases = select_complete_cases(
            case_files,
            require_div=require_div,
            extra_core_sources=extra_sources,
        )
    total_cases = len(complete_cases)

    for idx, (case_key, source_map) in enumerate(complete_cases, start=1):
        print(
            f"[{idx}/{total_cases}] case dgp={case_key.dgp_code}, n={case_key.n_train}, "
            f"rho={case_key.rho_eps_key}, seed={case_key.seed}"
        )

        deepcf_by_x = load_model_samples_by_x(source_map["deepcf"], model="estimated")
        indep_by_x = load_model_samples_by_x(source_map["deepcf"], model="independence")
        tab_by_x = load_model_samples_by_x(source_map["tabpfn-naive"], model="estimated")
        oracle_by_x = load_model_samples_by_x(source_map["oracle"], model="oracle")
        extra_by_source = {
            source: load_model_samples_by_x(source_map[source], model="estimated")
            for source in extra_sources
        }
        div_by_x = load_model_samples_by_x(source_map["div"], model="estimated") if "div" in source_map else {}

        x_keys = sorted(set(deepcf_by_x) & set(indep_by_x) & set(tab_by_x) & set(oracle_by_x))
        for source in extra_sources:
            x_keys = sorted(set(x_keys) & set(extra_by_source[source]))
        if not x_keys:
            print(
                "  skip: no overlapping x between required model slices "
                f"for seed={case_key.seed}"
            )
            continue

        for x_key in x_keys:
            x_val = oracle_by_x[x_key][0]
            core_pts, core_w = deepcf_by_x[x_key][1], deepcf_by_x[x_key][2]
            indep_pts, indep_w = indep_by_x[x_key][1], indep_by_x[x_key][2]
            tab_pts, tab_w = tab_by_x[x_key][1], tab_by_x[x_key][2]
            ref_pts, ref_w = oracle_by_x[x_key][1], oracle_by_x[x_key][2]
            extra_points: dict[str, tuple[np.ndarray, np.ndarray]] = {}
            for source in extra_sources:
                extra_pts, extra_w = extra_by_source[source][x_key][1], extra_by_source[source][x_key][2]
                extra_points[source] = (extra_pts, extra_w)
            div_pts = div_w = None
            if x_key in div_by_x:
                div_pts, div_w = div_by_x[x_key][1], div_by_x[x_key][2]

            core_pts, core_w = _downsample_points(
                core_pts,
                core_w,
                max_n=max_samples_per_dist,
                seed=_stable_seed(random_seed, case_key, x_key, "core"),
            )
            indep_pts, indep_w = _downsample_points(
                indep_pts,
                indep_w,
                max_n=max_samples_per_dist,
                seed=_stable_seed(random_seed, case_key, x_key, "indep"),
            )
            tab_pts, tab_w = _downsample_points(
                tab_pts,
                tab_w,
                max_n=max_samples_per_dist,
                seed=_stable_seed(random_seed, case_key, x_key, "tab"),
            )
            for source in extra_sources:
                extra_pts, extra_w = extra_points[source]
                extra_points[source] = _downsample_points(
                    extra_pts,
                    extra_w,
                    max_n=max_samples_per_dist,
                    seed=_stable_seed(random_seed, case_key, x_key, source),
                )
            ref_pts, ref_w = _downsample_points(
                ref_pts,
                ref_w,
                max_n=max_samples_per_dist,
                seed=_stable_seed(random_seed, case_key, x_key, "oracle"),
            )
            if div_pts is not None and div_w is not None:
                div_pts, div_w = _downsample_points(
                    div_pts,
                    div_w,
                    max_n=max_samples_per_dist,
                    seed=_stable_seed(random_seed, case_key, x_key, "div"),
                )

            core_dist = compute_wasserstein_distance(
                core_pts, ref_pts, core_w, ref_w, method=method, directions=directions
            )
            tab_dist = compute_wasserstein_distance(
                tab_pts, ref_pts, tab_w, ref_w, method=method, directions=directions
            )
            indep_dist = compute_wasserstein_distance(
                indep_pts, ref_pts, indep_w, ref_w, method=method, directions=directions
            )
            extra_dists: dict[str, float] = {}
            for source in extra_sources:
                extra_pts, extra_w = extra_points[source]
                extra_dists[source] = compute_wasserstein_distance(
                    extra_pts,
                    ref_pts,
                    extra_w,
                    ref_w,
                    method=method,
                    directions=directions,
                )
            div_dist = np.nan
            if div_pts is not None and div_w is not None:
                div_dist = compute_wasserstein_distance(
                    div_pts, ref_pts, div_w, ref_w, method=method, directions=directions
                )

            row: dict[str, float | int | str] = {
                "dgp_code": case_key.dgp_code,
                "n_train": int(case_key.n_train),
                "rho_eps": float(case_key.rho_eps_key),
                "seed": int(case_key.seed),
                "x": float(x_val),
                "core_vs_oracle_wdist": float(core_dist),
                "tabpfn_naive_vs_oracle_wdist": float(tab_dist),
                "independence_vs_oracle_wdist": float(indep_dist),
                "div_vs_oracle_wdist": float(div_dist) if np.isfinite(div_dist) else np.nan,
                "n_points_core": int(len(core_pts)),
                "n_points_tabpfn": int(len(tab_pts)),
                "n_points_independence": int(len(indep_pts)),
                "n_points_div": int(len(div_pts)) if div_pts is not None else 0,
                "n_points_oracle": int(len(ref_pts)),
            }
            for source in extra_sources:
                extra_pts, _ = extra_points[source]
                row[f"{source}_vs_oracle_wdist"] = float(extra_dists[source])
                row[f"n_points_{source}"] = int(len(extra_pts))
            rows.append(row)

    return pd.DataFrame(rows)


def aggregate_case_x(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df.copy()
    agg_spec: dict[str, tuple[str, str]] = {
        "n_seed": ("seed", "nunique"),
        "core_vs_oracle_mean": ("core_vs_oracle_wdist", "mean"),
        "core_vs_oracle_std": ("core_vs_oracle_wdist", "std"),
        "tabpfn_naive_vs_oracle_mean": ("tabpfn_naive_vs_oracle_wdist", "mean"),
        "tabpfn_naive_vs_oracle_std": ("tabpfn_naive_vs_oracle_wdist", "std"),
        "independence_vs_oracle_mean": ("independence_vs_oracle_wdist", "mean"),
        "independence_vs_oracle_std": ("independence_vs_oracle_wdist", "std"),
        "div_vs_oracle_mean": ("div_vs_oracle_wdist", "mean"),
        "div_vs_oracle_std": ("div_vs_oracle_wdist", "std"),
    }
    for source in KNOWN_EXTRA_CORE_SOURCES:
        distance_col = f"{source}_vs_oracle_wdist"
        if distance_col in df.columns:
            agg_spec[f"{source}_vs_oracle_mean"] = (distance_col, "mean")
            agg_spec[f"{source}_vs_oracle_std"] = (distance_col, "std")
    out = df.groupby(["dgp_code", "n_train", "rho_eps", "x"], as_index=False).agg(**agg_spec)
    out = out.sort_values(["dgp_code", "n_train", "rho_eps", "x"]).reset_index(drop=True)
    return out


def aggregate_case(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df.copy()
    agg_spec: dict[str, tuple[str, str]] = {
        "n_seed": ("seed", "nunique"),
        "n_x": ("x", "nunique"),
        "n_seed_x": ("x", "count"),
        "core_vs_oracle_mean": ("core_vs_oracle_wdist", "mean"),
        "core_vs_oracle_std": ("core_vs_oracle_wdist", "std"),
        "tabpfn_naive_vs_oracle_mean": ("tabpfn_naive_vs_oracle_wdist", "mean"),
        "tabpfn_naive_vs_oracle_std": ("tabpfn_naive_vs_oracle_wdist", "std"),
        "independence_vs_oracle_mean": ("independence_vs_oracle_wdist", "mean"),
        "independence_vs_oracle_std": ("independence_vs_oracle_wdist", "std"),
        "div_vs_oracle_mean": ("div_vs_oracle_wdist", "mean"),
        "div_vs_oracle_std": ("div_vs_oracle_wdist", "std"),
    }
    for source in KNOWN_EXTRA_CORE_SOURCES:
        distance_col = f"{source}_vs_oracle_wdist"
        if distance_col in df.columns:
            agg_spec[f"{source}_vs_oracle_mean"] = (distance_col, "mean")
            agg_spec[f"{source}_vs_oracle_std"] = (distance_col, "std")
    out = df.groupby(["dgp_code", "n_train", "rho_eps"], as_index=False).agg(**agg_spec)
    out = out.sort_values(["dgp_code", "n_train", "rho_eps"]).reset_index(drop=True)
    return out


def plot_case_x(
    case_x_df: pd.DataFrame,
    *,
    plot_dir: Path,
    method: str,
) -> int:
    if case_x_df.empty:
        return 0

    plot_dir.mkdir(parents=True, exist_ok=True)
    for old_plot in plot_dir.glob("wasserstein_case_*.png"):
        old_plot.unlink()

    n_plots = 0
    colors = {
        "core_vs_oracle": "#1f77b4",
        "tabpfn_naive_vs_oracle": "#d62728",
        "independence_vs_oracle": "#2ca02c",
    }

    series = [
        ("core_vs_oracle_mean", "core_vs_oracle_std", "Core vs Oracle", colors["core_vs_oracle"]),
    ]
    for source in KNOWN_EXTRA_CORE_SOURCES:
        mean_col = f"{source}_vs_oracle_mean"
        if mean_col in case_x_df.columns and not case_x_df[mean_col].isna().all():
            series.append(
                (
                    mean_col,
                    f"{source}_vs_oracle_std",
                    EXTRA_SOURCE_LABELS[source],
                    EXTRA_SOURCE_COLORS[source],
                )
            )
    series.extend(
        [
            (
                "tabpfn_naive_vs_oracle_mean",
                "tabpfn_naive_vs_oracle_std",
                "TabPFN-naive vs Oracle",
                colors["tabpfn_naive_vs_oracle"],
            ),
            (
                "independence_vs_oracle_mean",
                "independence_vs_oracle_std",
                "Independence vs Oracle",
                colors["independence_vs_oracle"],
            ),
        ]
    )
    if "div_vs_oracle_mean" in case_x_df.columns and not case_x_df["div_vs_oracle_mean"].isna().all():
        colors["div_vs_oracle"] = "#8c564b"
        series.append(
            ("div_vs_oracle_mean", "div_vs_oracle_std", "DIV vs Oracle", colors["div_vs_oracle"])
        )

    for dgp_code, dgp_df in case_x_df.groupby("dgp_code", sort=True):
        rho_values = sorted(float(v) for v in dgp_df["rho_eps"].dropna().unique())
        n_values = sorted(int(v) for v in dgp_df["n_train"].dropna().unique())
        if not rho_values or not n_values:
            continue
        rho_array = dgp_df["rho_eps"].to_numpy(dtype=float)
        n_train_array = dgp_df["n_train"].to_numpy(dtype=int)

        n_rows = len(rho_values)
        n_cols = len(n_values)
        fig, axes = plt.subplots(
            n_rows,
            n_cols,
            squeeze=False,
            sharex=True,
            sharey=True,
            figsize=(5.0 * n_cols, 3.6 * n_rows),
        )

        legend_handles = []
        legend_labels = []
        legend_set = False

        for row_idx, rho_eps in enumerate(rho_values):
            for col_idx, n_train in enumerate(n_values):
                ax = axes[row_idx, col_idx]
                mask = (n_train_array == n_train) & np.isclose(rho_array, rho_eps)
                g = dgp_df.loc[mask].sort_values("x")

                if g.empty:
                    ax.text(
                        0.5,
                        0.5,
                        "No data",
                        ha="center",
                        va="center",
                        transform=ax.transAxes,
                        fontsize=10,
                        color="#555555",
                    )
                else:
                    x = g["x"].to_numpy(dtype=float)
                    for mean_col, std_col, label, color in series:
                        mean_vals = g[mean_col].to_numpy(dtype=float)
                        std_vals = g[std_col].fillna(0.0).to_numpy(dtype=float)
                        (line,) = ax.plot(x, mean_vals, color=color, linewidth=2.0)
                        ax.fill_between(
                            x,
                            np.maximum(0.0, mean_vals - std_vals),
                            mean_vals + std_vals,
                            color=color,
                            alpha=0.16,
                            linewidth=0.0,
                        )
                        if not legend_set:
                            legend_handles.append(line)
                            legend_labels.append(label)
                    legend_set = True

                ax.set_title(f"n={int(n_train)} | rho_eps={float(rho_eps):.3f}")
                ax.grid(alpha=0.25, linestyle="--", linewidth=0.8)

        fig.suptitle(f"{dgp_code} | Wasserstein vs Oracle ({method})")
        fig.supxlabel("Intervention x")
        fig.supylabel(f"Wasserstein Distance ({method})")
        if legend_handles:
            fig.legend(
                legend_handles,
                legend_labels,
                loc="upper center",
                ncol=3,
                frameon=False,
                bbox_to_anchor=(0.5, 0.98),
            )

        fname = f"wasserstein_case_{dgp_code}_grid.png"
        fig.tight_layout(rect=(0.02, 0.02, 0.98, 0.93))
        fig.savefig(plot_dir / fname, dpi=220)
        plt.close(fig)
        n_plots += 1

    return n_plots


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Compute Wasserstein-vs-oracle metrics from multivariate sample outputs.")
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=Path("multivar/io/results"),
        help="Results directory that contains per_run outputs.",
    )
    parser.add_argument(
        "--per-run-dir",
        type=Path,
        default=None,
        help="Optional explicit per_run directory. Defaults to <results-dir>/per_run.",
    )
    parser.add_argument(
        "--aggregated-dir",
        type=Path,
        default=Path("multivar/io/aggregated"),
        help="Directory to write aggregated outputs and plots.",
    )
    parser.add_argument(
        "--output-prefix",
        type=str,
        default="evaluate_wasserstein",
        help="Prefix for output file names.",
    )
    parser.add_argument(
        "--n-train",
        type=int,
        default=None,
        help="Optional training sample size filter applied before aggregation and plotting.",
    )
    parser.add_argument(
        "--dgp-codes",
        nargs="+",
        default=None,
        help="Optional DGP-code filter applied before aggregation and plotting. Aliases are accepted.",
    )
    parser.add_argument(
        "--method",
        choices=["sliced", "nd"],
        default="sliced",
        help="Distance method: sliced (fast approximation) or nd (exact if SciPy supports it).",
    )
    parser.add_argument(
        "--n-projections",
        type=int,
        default=128,
        help="Number of random projections when --method sliced.",
    )
    parser.add_argument(
        "--max-samples-per-dist",
        type=int,
        default=None,
        help="Optional downsample cap per distribution before distance computation.",
    )
    parser.add_argument(
        "--random-seed",
        type=int,
        default=20260304,
        help="Random seed for projection directions and optional downsampling.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail when any case is missing one of {deepcf, tabpfn-naive, oracle}.",
    )
    parser.add_argument(
        "--require-div",
        action="store_true",
        help="Upgrade completeness checks to require DIV in addition to {deepcf, tabpfn-naive, oracle}.",
    )
    parser.add_argument(
        "--extra-core-sources",
        nargs="+",
        default=(),
        choices=list(KNOWN_EXTRA_CORE_SOURCES),
        help="Optional extra core marginal sources to require and compare against oracle.",
    )
    parser.add_argument(
        "--case-shard-count",
        type=int,
        default=1,
        help="Split complete cases into this many shards and process only one shard when used with --case-shard-index.",
    )
    parser.add_argument(
        "--case-shard-index",
        type=int,
        default=0,
        help="0-indexed shard selection applied after complete-case filtering.",
    )
    parser.add_argument(
        "--detail-only",
        action="store_true",
        help="Write only the seed-x detail CSV and skip case aggregation/plots.",
    )
    parser.add_argument(
        "--merge-detail-glob",
        type=str,
        default=None,
        help="Glob pattern for precomputed detail CSV shards to merge instead of recomputing Wasserstein distances.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    aggregated_dir = args.aggregated_dir.resolve()
    aggregated_dir.mkdir(parents=True, exist_ok=True)
    extra_core_sources = _normalize_extra_core_sources(args.extra_core_sources)

    if args.merge_detail_glob:
        detail_df = load_detail_parts(args.merge_detail_glob)
        print(f"Merged detail CSVs from glob: {args.merge_detail_glob}")
    else:
        per_run_dir = args.per_run_dir or (args.results_dir / "per_run")
        per_run_dir = per_run_dir.resolve()
        if not per_run_dir.exists():
            raise FileNotFoundError(f"per_run directory not found: {per_run_dir}")

        case_files, skipped = discover_case_files(per_run_dir)
        raw_case_count = len(case_files)
        selected_dgp_codes = _normalize_dgp_codes(args.dgp_codes)
        case_files = filter_case_files(
            case_files,
            n_train=args.n_train,
            dgp_codes=selected_dgp_codes,
        )
        required_sources = _required_sources(require_div=args.require_div, extra_core_sources=extra_core_sources)
        complete_cases = select_complete_cases(
            case_files,
            require_div=args.require_div,
            extra_core_sources=extra_core_sources,
        )
        incomplete_cases = [k for k, v in case_files.items() if not all(src in v for src in required_sources)]

        print(f"Discovered distribution sample files under: {per_run_dir}")
        print(f"Total candidate cases before filters: {raw_case_count}")
        if args.n_train is not None:
            print(f"Applied n_train filter: {int(args.n_train)}")
        if selected_dgp_codes:
            print(f"Applied dgp_code filter: {', '.join(selected_dgp_codes)}")
        if extra_core_sources:
            print(f"Requested extra core sources: {', '.join(extra_core_sources)}")
        print(f"Candidate cases after filters: {len(case_files)}")
        print(f"Complete cases ({'/'.join(required_sources)}): {len(complete_cases)}")
        print(f"Incomplete cases: {len(incomplete_cases)}")
        print(f"Skipped files during discovery: {skipped}")

        if args.strict and incomplete_cases:
            preview = ", ".join(
                f"{k.dgp_code}|n={k.n_train}|rho={k.rho_eps_key}|seed={k.seed}" for k in incomplete_cases[:5]
            )
            raise RuntimeError(
                f"Found {len(incomplete_cases)} incomplete cases; examples: {preview}"
            )
        if not complete_cases:
            need = " + ".join(required_sources)
            raise RuntimeError(f"No complete cases found. Need {need} distribution samples.")

        sharded_cases = shard_complete_cases(
            complete_cases,
            shard_count=args.case_shard_count,
            shard_index=args.case_shard_index,
        )
        print(
            f"Processing case shard {args.case_shard_index + 1}/{args.case_shard_count}: "
            f"{len(sharded_cases)} cases"
        )
        if not sharded_cases:
            raise RuntimeError(
                f"Selected case shard {args.case_shard_index + 1}/{args.case_shard_count} is empty."
            )

        directions = None
        if args.method == "sliced":
            directions = _build_projection_directions(args.n_projections, args.random_seed)

        detail_df = compute_seed_x_metrics(
            case_files=None,
            require_div=args.require_div,
            extra_core_sources=extra_core_sources,
            method=args.method,
            directions=directions,
            max_samples_per_dist=args.max_samples_per_dist,
            random_seed=args.random_seed,
            complete_cases=sharded_cases,
        )
        if detail_df.empty:
            raise RuntimeError("No Wasserstein rows computed. Check model/x overlaps in per-run files.")

    detail_df["method"] = args.method
    detail_df["n_projections"] = int(args.n_projections if args.method == "sliced" else 0)
    detail_df["max_samples_per_dist"] = (
        int(args.max_samples_per_dist) if args.max_samples_per_dist is not None else -1
    )
    detail_df = detail_df.sort_values(["dgp_code", "n_train", "rho_eps", "seed", "x"]).reset_index(drop=True)

    case_x_df = aggregate_case_x(detail_df)
    case_df = aggregate_case(detail_df)

    detail_path = aggregated_dir / f"{args.output_prefix}_seed_x.csv"
    case_x_path = aggregated_dir / f"{args.output_prefix}_case_x.csv"
    case_path = aggregated_dir / f"{args.output_prefix}_case_summary.csv"
    plot_dir = aggregated_dir / f"{args.output_prefix}_plots"

    detail_df.to_csv(detail_path, index=False)
    print(f"Wrote seed-x metrics: {detail_path} ({len(detail_df)} rows)")
    if args.detail_only:
        return

    case_x_df.to_csv(case_x_path, index=False)
    case_df.to_csv(case_path, index=False)
    n_plots = plot_case_x(case_x_df, plot_dir=plot_dir, method=args.method)
    print(f"Wrote case-x summary: {case_x_path} ({len(case_x_df)} rows)")
    print(f"Wrote case summary: {case_path} ({len(case_df)} rows)")
    print(f"Wrote case plots: {plot_dir} ({n_plots} files)")


if __name__ == "__main__":
    main()
